version: '2.0'
services:
  ui:
    build: ./
    # image: idobry/chartmuseumui:latest
    environment:
      CHART_MUSEUM_URL: http://chartmuseum:8080
    ports:
      - 3000:8080
  chartmuseum:
    image: bitnami/chartmuseum:0.15.0
    ports:
    - 80:8080
    volumes:
    - /data:/bitnami/data
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      # STORAGE_LOCAL_ROOTDIR: /charts
    user: root
